java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

dependencies {
    compileOnly(project(":fakeplayer-core"))
    compileOnly(project(":fakeplayer-api"))
    compileOnly(project(":fakeplayer-v1_20_1"))
    compileOnly(project(":fakeplayer-v1_20_2"))
    compileOnly(project(":fakeplayer-v1_20_3"))
    compileOnly(project(":fakeplayer-v1_20_4"))
    compileOnly(project(":fakeplayer-v1_20_5"))
    compileOnly(project(":fakeplayer-v1_20_6"))
    compileOnly(project(":fakeplayer-v1_21"))
    compileOnly(project(":fakeplayer-v1_21_1"))
    compileOnly(project(":fakeplayer-v1_21_3"))
    compileOnly(project(":fakeplayer-v1_21_4"))
    compileOnly(project(":fakeplayer-v1_21_5"))
    compileOnly(project(":fakeplayer-v1_21_6"))
    compileOnly(project(":fakeplayer-v1_21_7"))
    compileOnly(project(":fakeplayer-v1_21_8"))
    compileOnly(project(":fakeplayer-v1_21_9"))
    compileOnly(project(":fakeplayer-v1_21_10"))
    compileOnly(project(":fakeplayer-v1_21_11"))
}

tasks.register<Jar>("shadowJar") {
    archiveFileName.set("fakeplayer-fp.build1.jar")
    dependsOn(":fakeplayer-core:build")
    dependsOn(":fakeplayer-api:build")
    dependsOn(":fakeplayer-v1_20_1:build")
    dependsOn(":fakeplayer-v1_20_2:build")
    dependsOn(":fakeplayer-v1_20_3:build")
    dependsOn(":fakeplayer-v1_20_4:build")
    dependsOn(":fakeplayer-v1_20_5:build")
    dependsOn(":fakeplayer-v1_20_6:build")
    dependsOn(":fakeplayer-v1_21:build")
    dependsOn(":fakeplayer-v1_21_1:build")
    dependsOn(":fakeplayer-v1_21_3:build")
    dependsOn(":fakeplayer-v1_21_4:build")
    dependsOn(":fakeplayer-v1_21_5:build")
    dependsOn(":fakeplayer-v1_21_6:build")
    dependsOn(":fakeplayer-v1_21_7:build")
    dependsOn(":fakeplayer-v1_21_8:build")
    dependsOn(":fakeplayer-v1_21_9:build")
    dependsOn(":fakeplayer-v1_21_10:build")
    dependsOn(":fakeplayer-v1_21_11:build")

    from(project(":fakeplayer-core").sourceSets.main.get().output)
    from(project(":fakeplayer-api").sourceSets.main.get().output)
    from(project(":fakeplayer-v1_20_1").sourceSets.main.get().output)
    from(project(":fakeplayer-v1_20_2").sourceSets.main.get().output)
    from(project(":fakeplayer-v1_20_3").sourceSets.main.get().output)
    from(project(":fakeplayer-v1_20_4").sourceSets.main.get().output)
    from(project(":fakeplayer-v1_20_5").sourceSets.main.get().output)
    from(project(":fakeplayer-v1_20_6").sourceSets.main.get().output)
    from(project(":fakeplayer-v1_21").sourceSets.main.get().output)
    from(project(":fakeplayer-v1_21_1").sourceSets.main.get().output)
    from(project(":fakeplayer-v1_21_3").sourceSets.main.get().output)
    from(project(":fakeplayer-v1_21_4").sourceSets.main.get().output)
    from(project(":fakeplayer-v1_21_5").sourceSets.main.get().output)
    from(project(":fakeplayer-v1_21_6").sourceSets.main.get().output)
    from(project(":fakeplayer-v1_21_7").sourceSets.main.get().output)
    from(project(":fakeplayer-v1_21_8").sourceSets.main.get().output)
    from(project(":fakeplayer-v1_21_9").sourceSets.main.get().output)
    from(project(":fakeplayer-v1_21_10").sourceSets.main.get().output)
    from(project(":fakeplayer-v1_21_11").sourceSets.main.get().output)
}
